// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_events.h"
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_UserPanel;
extern lv_obj_t * ui_UserImage;
extern lv_obj_t * ui_TimeLable;
extern lv_obj_t * ui_WelcomeLabel;
extern lv_obj_t * ui_DateLabel;
extern lv_obj_t * ui_HumidityPanel;
extern lv_obj_t * ui_ChineseHumLabel;
extern lv_obj_t * ui_HumImage;
extern lv_obj_t * ui_HumidityLable;
extern lv_obj_t * ui_HumLable;
extern lv_obj_t * ui_TempPanel;
extern lv_obj_t * ui_ChineseTempLabel;
extern lv_obj_t * ui_TempImage;
extern lv_obj_t * ui_TemperatureLable;
extern lv_obj_t * ui_TempLable;
extern lv_obj_t * ui_WeatherPanel;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_user_png);    // assets\user.png
LV_IMG_DECLARE(ui_img_humidity_png);    // assets\humidity.png
LV_IMG_DECLARE(ui_img_temperature_png);    // assets\temperature.png
LV_IMG_DECLARE(ui_img_sunny_png);    // assets\Sunny.png
LV_IMG_DECLARE(ui_img_light_png);    // assets\light.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
