/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "msg.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(TemperatureAndHumidity, TemperatureAndHumidity, AUTO)


PB_BIND(LedSwitch, LedSwitch, AUTO)


PB_BIND(SensorIn, SensorIn, AUTO)




